version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - 'type: dependencies'
      - 'github-actions'

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    labels:
      - 'type: dependencies'
      - 'docker'
