---

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - 'merge-strategy: rebase'
      - 'type: dependencies'
      - 'github-actions'

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    labels:
      - 'merge-strategy: rebase'
      - 'type: dependencies'
      - 'docker'

  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: weekly
    labels:
      - 'merge-strategy: rebase'
      - 'type: dependencies'
      - 'git-submodule'
