---

name: Differential ShellCheck
description: Differential ShellCheck

branding:
  icon: check-circle
  color: green

inputs:
  base:
    description: Repository base
    required: true
    default: ${{ github.event.pull_request.base.sha }}
  head:
    description: Head of changes
    required: true
    default: ${{ github.event.pull_request.head.sha }}
  ignored-codes:
    description: List of ShellCheck codes which should be excluded from validation
    required: false
  shell-scripts:
    description: List of Shell scripts proposed for validation
    required: false
  severity:
    description: Specify minimum severity of errors to consider. Valid values in order of severity are error, warning, info and style. The default is style.
    default: style
    required: false
  token:
    description: GitHub TOKEN used to upload SARIF data
    required: false

outputs:
  result:
    description: Result of Differential ShellCheck

runs:
  using: docker
  image: docker://ghcr.io/redhat-plumbers-in-action/differential-shellcheck:v2.4.0
  env:
    INPUT_IGNORED_CODES: ${{ inputs.ignored-codes }}
    INPUT_SHELL_SCRIPTS: ${{ inputs.shell-scripts }}
