# SPDX-License-Identifier: GPL-3.0-or-later
---

name: Differential ShellCheck
description: Differential ShellCheck

branding:
  icon: check-circle
  color: green

inputs:
  base:
    description: Repository base
    required: true
    default: ${{ github.event.pull_request.base.sha }}
  head:
    description: Head of changes
    required: true
    default: ${{ github.event.pull_request.head.sha }}
  ignored-codes:
    description: List of ShellCheck codes which should be excluded from validation
    deprecationMessage: This option is now deprecated, please consider using `.shellcheckrc` instead.
    required: false
  shell-scripts:
    description: List of Shell scripts proposed for validation
    required: false
  external-sources:
    description: |
      Enable following of source statements even when the file is not specified as input. By default, shellcheck will only follow files specified on the command-line (plus /dev/null).
      This option allows following any file the script may source. This option may also be enabled using external-sources=true in .shellcheckrc. This flag takes precedence.
    default: 'true'
    required: false
  severity:
    description: Specify minimum severity of errors to consider. Valid values in order of severity are error, warning, info and style. The default is style.
    default: style
    required: false
  token:
    description: GitHub TOKEN used to upload SARIF data
    required: false

outputs:
  result:
    description: Result of Differential ShellCheck

runs:
  using: docker
  image: docker://ghcr.io/redhat-plumbers-in-action/differential-shellcheck:v3.3.0
  env:
    INPUT_IGNORED_CODES: ${{ inputs.ignored-codes }}
    INPUT_SHELL_SCRIPTS: ${{ inputs.shell-scripts }}
    INPUT_EXTERNAL_SOURCES: ${{ inputs.external-sources }}
