---

name: Report an Issue
description: Issue form for reporting issues and requesting new features.

body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this issue!

  - type: dropdown
    id: type
    attributes:
      label: Type of issue
      multiple: false
      options:
        - 'Bug Report'
        - 'Feature Request'
        - 'other'
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the problem is. E.g. I'm always frustrated when [...]
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: false
