name: Containers

on:
  schedule:
    -  cron: 0 6 * * *
  push:
    branches: [ main ]
    paths:
      - container/**
      - .github/workflows/container.yml
  pull_request:
    branches: [ main ]
    paths:
      - container/**
      - .github/workflows/container.yml
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

permissions:
  packages: write
  contents: read

jobs:
  push_to_registry:
    name: Build and push containers
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.config.dockerfile }}
      cancel-in-progress: true

    strategy:
      fail-fast: false
      matrix:
        config:
          - { dockerfile: 'action.Dockerfile', tag: 'differential-shellcheck' }
          - { dockerfile: 'test.Dockerfile', tag: 'bats-kcov' }

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Container
        uses: docker/build-push-action@v3
        with:
          file: container/${{ matrix.config.dockerfile }}
          tags: ${{ env.REGISTRY }}/${{ github.repository }}/${{ matrix.config.tag }}:latest
          push: ${{ github.event_name == 'push' ||  github.event_name == 'schedule' }}
