---

name: Pull Request Labeler
on:
  pull_request_target:

permissions:
  contents: read

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 #v5.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
