---

name: Pull Request Labeler
on:
  pull_request_target:

permissions:
  contents: read

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b #v6.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
