---

name: GitHub Tag Update

on:
  release:
    types: [ published, edited ]

permissions:
  contents: read

jobs:
  actions-tagger:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Repository checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

        # never use pinning to SHA, it breaks the release of this action
      - name: Update tag
        uses: Actions-R-Us/actions-tagger@v2
        with:
          publish_latest_tag: false
          token: ${{ secrets.GITHUB_TOKEN }}
