---

name: Release Drafter

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  update_release_draft:
    name: Update release Draft
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
