name: Test Differential ShellCheck
on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  shellCheck:
    runs-on: ubuntu-20.04

    permissions:
      security-events: write

    steps:   
      - name: Repository checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Differential ShellCheck
        uses: ./
        with:
          ignored-codes: .github/.diff-shellcheck-exceptions.txt
          shell-scripts: .github/.diff-shellcheck-scripts.txt
          token: ${{ secrets.GITHUB_TOKEN }}
